title: Rajesh Kumar
email: kr.rajesh.phy@gmail.com
description: Lecture Notes
baseurl: "/SKMU"
url: "rajeshphy.github.io"   # REQUIRED in Jekyll 4 (set domain if deploying)

default_image: /assets/images/physics.jpeg

author:
  name: Rajesh Kumar
  twitter:
  picture:

twitter_username:
github_username:

logo: /assets/icons/logo.png

remote_theme: mmistakes/jekyll-theme-basically-basic

search: true
search_full_content: true
search_provider: lunr

comments: true
disqus:
  shortname: consultt-github-io

# -----------------
# Build settings
# -----------------
markdown: kramdown
# theme: jekyll-theme-basically-basic   # MUST be enabled (theme gem)

include:
  - assets

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# -----------------
# Feed
# -----------------
feed:
  path: feed.xml   # URL NOT allowed here in Jekyll 4

# -----------------
# Pagination
# -----------------
paginate: 20
paginate_path: "/page:num/"

# -----------------
# Front Matter Defaults
# -----------------
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true